### ISSUE TITLE
Seems instruction for maintainers not up to date

### ISSUE THREAD

**Issue by KirillSelyak** [mathiasbynens/emoji-test-regex-pattern#24]
Hello,

First of all thank you for the project, it is really useful and awesome! 
I have found that emoji **\u2388** is missed and try to contribute here.  
I'm stuck with [instruction for maintainers](https://github.com/mathiasbynens/emoji-test-regex-pattern#for-maintainers) at 1st step
Is instruction up to date? 
**Steps to reproduce**
1) clone git repository  => fine
2) run `npm install` => fine
2) run `npm install unicode-emoji-16.0@npm:@unicode/unicode-16.0.0@latest --save-dev` =>  `Not Found - GET https://registry.npmjs.org/@unicode%2funicode-16.0.0 - Not found`  

I have intuitive understanding and basic skills regarding npm, could imagine it might be an issue with my PC.
Should it work or may I miss something?

**Comment by mathiasbynens** [comment]
Hi @KirillSelyak!

> I have found that emoji `\u2388` is missed and try to contribute here.

U+2388 does not appear in https://www.unicode.org/Public/emoji/15.0/emoji-test.txt and should thus not be matched. What makes you say it's an emoji?

The instructions for maintainers are up to date. You're trying to install a package called `@unicode/unicode-16.0.0` which doesn't exist, since Unicode 16 hasn't been released yet.

**Comment by KirillSelyak** [comment]
Ok, 
It looks very similar to  `\u2638` 
![image](https://user-images.githubusercontent.com/12545192/194335597-3d0ac36e-21f2-4223-aae7-5f7e5d14f131.png)

Some resources refer to it but highlight it is unofficial - https://www.emojiall.com/en/emoji/%E2%8E%88
As far as `\u2388` is not official emoji then it is fine, no issue.
